# Generated by Django 2.1.3 on 2018-12-01 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_auto_20181201_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='job',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='job_comments', to='job.Job'),
        ),
    ]
