# Generated by Django 2.1.3 on 2018-12-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='picture',
            field=models.FileField(default=None, upload_to='', verbose_name='job_picture'),
        ),
    ]
