# Generated by Django 2.1.3 on 2018-12-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('job', '0003_job_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='tags',
            field=models.ManyToManyField(default=None, related_name='job_tags', to='user.Tag'),
        ),
    ]
