# Generated by Django 2.1.3 on 2018-12-01 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20181201_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desiredprofileitem',
            old_name='description',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='offereditem',
            old_name='description',
            new_name='label',
        ),
    ]
