# Generated by Django 2.1.3 on 2018-12-01 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import joberon.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0006_auto_20181201_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=joberon.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BonusEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=joberon.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('entry', models.CharField(db_index=True, max_length=100)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='job.Bonus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=joberon.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('text', models.TextField()),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_comments', to=settings.AUTH_USER_MODEL)),
                ('reply', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comment_replies', to='job.Comment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='desiredprofileitem',
            name='label',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='offereditem',
            name='label',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AddField(
            model_name='job',
            name='bonuses',
            field=models.ManyToManyField(default=None, related_name='job_bonuses', to='job.BonusEntry'),
        ),
    ]
