# Generated by Django 2.1.3 on 2018-12-01 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_auto_20181201_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bonusentry',
            old_name='name',
            new_name='bonus',
        ),
    ]
