# Generated by Django 2.1.3 on 2018-12-01 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_auto_20181201_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='job',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='job_comments', to='job.Job'),
        ),
    ]
