# Generated by Django 2.1.3 on 2018-12-01 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_comment_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_replies', to='job.Comment'),
        ),
    ]
