# Generated by Django 2.1.3 on 2018-12-01 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_auto_20181201_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='job',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='job_comments', to='job.Job'),
        ),
    ]
