# Generated by Django 2.1.3 on 2018-12-01 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_auto_20181201_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_user_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
