# Generated by Django 2.1.3 on 2019-02-06 17:30

from django.db import migrations, models
import django.db.models.deletion
import joberia.apps.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('spawner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=joberia.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('type', models.CharField(choices=[('dev', 'Developer'), ('org', 'Organization')], default=('dev', 'Developer'), max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_org', to='company.Organization')),
                ('platform_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='spawner.Platform', verbose_name='platform')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
